[build]
  command = "npm install && npm run build"
  functions = "functions"

[[redirects]]
  from = "/public"
  to = "/public"

[[redirects]]
  from = "/public/assets"
  to = "/public/assets"

[[redirects]]
  from = "/public/assets/taskfiles"
  to = "/public/assets/taskfiles"

[context.branch-deploy.environment]
  MODE = "dev"