[build]
  command = "npm install && npm run build"
  functions = "functions"

[[redirects]]
  from = "/public"
  to = "/.netlify/functions/api"

[[redirects]]
  from = "/public/assets/taskfiles"
  to = "/.netlify/functions/api"

[context.branch-deploy.environment]
  MODE = "dev"